version: '3.8'

services:
  perfilapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: perfilapp
    # ports:
    #   - "81:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy_network
    labels:
      - "traefik.http.routers.perfilapp.rule=Host(`william-as.com`) && PathPrefix(`/`)"
      #- "traefik.http.routers.perfilapp.rule=Host(`william-as.com`)"
      - "traefik.enable=true"
      #- "traefik.http.routers.perfilapp.rule=Host(`william-as.com`)"
      - "traefik.http.routers.perfilapp.entrypoints=web"
      - "traefik.http.services.perfilapp.loadbalancer.server.port=80"

networks:
  proxy_network:
    external: true
